/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NoteIdentifier = IDL.Text;
export const DocumentIdentifier = IDL.Text;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookmarkNote' : IDL.Func([NoteIdentifier], [], []),
  'bookmarkVideo' : IDL.Func([DocumentIdentifier], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNoteBookmarks' : IDL.Func([], [IDL.Vec(NoteIdentifier)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoBookmarks' : IDL.Func([], [IDL.Vec(DocumentIdentifier)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unbookmarkNote' : IDL.Func([NoteIdentifier], [], []),
  'unbookmarkVideo' : IDL.Func([DocumentIdentifier], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NoteIdentifier = IDL.Text;
  const DocumentIdentifier = IDL.Text;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookmarkNote' : IDL.Func([NoteIdentifier], [], []),
    'bookmarkVideo' : IDL.Func([DocumentIdentifier], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNoteBookmarks' : IDL.Func([], [IDL.Vec(NoteIdentifier)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoBookmarks' : IDL.Func(
        [],
        [IDL.Vec(DocumentIdentifier)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unbookmarkNote' : IDL.Func([NoteIdentifier], [], []),
    'unbookmarkVideo' : IDL.Func([DocumentIdentifier], [], []),
  });
};

export const init = ({ IDL }) => { return []; };