/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ThirdPaperVideo {
    title: string;
    youtubeUrl: string;
}
export interface SecondPaperVideo {
    title: string;
    youtubeUrl: string;
}
export interface SyllabusEntry {
    driveUrl: string;
    title: string;
    published: boolean;
    description: string;
}
export interface StandaloneVideo {
    title: string;
    description: string;
    youtubeUrl: string;
}
export interface StandaloneNote {
    driveUrl: string;
    title: string;
    description: string;
}
export interface SecondPaperTopic {
    title: string;
    description: string;
}
export interface SecondPaperNote {
    title: string;
    content: string;
}
export interface IQVideo {
    title: string;
    youtubeUrl: string;
}
export interface GKVideo {
    title: string;
    youtubeUrl: string;
}
export interface ThirdPaperTopic {
    title: string;
    description: string;
}
export interface IQCategory {
    title: string;
    description: string;
}
export interface GKTopic {
    title: string;
    description: string;
}
export interface IQNote {
    title: string;
    content: string;
}
export interface GKNote {
    title: string;
    content: string;
}
export type DocumentIdentifier = string;
export interface ThirdPaperNote {
    title: string;
    content: string;
}
export interface OldQuestion {
    title: string;
    year: bigint;
    paperType: string;
    pdfUrl: string;
}
export type NoteIdentifier = string;
export interface UserProfile {
    name: string;
}
export interface MockExam {
    title: string;
    duration: bigint;
    description: string;
    pdfUrl: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / *********
     * /    * Comments *
     * /    ***********
     */
    addComment(comment: string, replyId: bigint): Promise<void>;
    addGKNote(note: GKNote): Promise<void>;
    addGKTopic(topic: GKTopic): Promise<void>;
    addGKVideo(video: GKVideo): Promise<void>;
    addIQCategory(category: IQCategory): Promise<void>;
    addIQNote(note: IQNote): Promise<void>;
    addIQVideo(video: IQVideo): Promise<void>;
    addMockExam(exam: MockExam): Promise<void>;
    addOldQuestion(question: OldQuestion): Promise<void>;
    addSecondPaperNote(note: SecondPaperNote): Promise<void>;
    addSecondPaperTopic(topic: SecondPaperTopic): Promise<void>;
    addSecondPaperVideo(video: SecondPaperVideo): Promise<void>;
    addStandaloneNote(note: StandaloneNote): Promise<void>;
    addStandaloneVideo(video: StandaloneVideo): Promise<void>;
    addSyllabusEntry(entry: SyllabusEntry): Promise<void>;
    addThirdPaperNote(note: ThirdPaperNote): Promise<void>;
    addThirdPaperTopic(topic: ThirdPaperTopic): Promise<void>;
    addThirdPaperVideo(video: ThirdPaperVideo): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookmarkNote(noteId: NoteIdentifier): Promise<void>;
    bookmarkVideo(documentId: DocumentIdentifier): Promise<void>;
    deleteGKTopic(index: bigint): Promise<void>;
    deleteGKVideo(index: bigint): Promise<void>;
    deleteIQCategory(index: bigint): Promise<void>;
    deleteIQVideo(index: bigint): Promise<void>;
    deleteMockExam(index: bigint): Promise<void>;
    deleteOldQuestion(index: bigint): Promise<void>;
    deleteSecondPaperTopic(index: bigint): Promise<void>;
    deleteSecondPaperVideo(index: bigint): Promise<void>;
    deleteStandaloneNote(index: bigint): Promise<void>;
    deleteStandaloneVideo(index: bigint): Promise<void>;
    deleteSyllabusEntry(index: bigint): Promise<void>;
    deleteThirdPaperTopic(index: bigint): Promise<void>;
    deleteThirdPaperVideo(index: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getComments(): Promise<Array<Array<string>>>;
    getGKNotes(): Promise<Array<GKNote>>;
    getGKTopics(): Promise<Array<GKTopic>>;
    getGKVideos(): Promise<Array<GKVideo>>;
    getIQCategories(): Promise<Array<IQCategory>>;
    getIQNotes(): Promise<Array<IQNote>>;
    getIQVideos(): Promise<Array<IQVideo>>;
    getMockExams(): Promise<Array<MockExam>>;
    getNoteBookmarks(): Promise<Array<NoteIdentifier>>;
    getOldQuestions(): Promise<Array<OldQuestion>>;
    getSecondPaperNotes(): Promise<Array<SecondPaperNote>>;
    getSecondPaperTopics(): Promise<Array<SecondPaperTopic>>;
    getSecondPaperVideos(): Promise<Array<SecondPaperVideo>>;
    getStandaloneNotes(): Promise<Array<StandaloneNote>>;
    getStandaloneVideos(): Promise<Array<StandaloneVideo>>;
    getSyllabusEntries(): Promise<Array<SyllabusEntry>>;
    getThirdPaperNotes(): Promise<Array<ThirdPaperNote>>;
    getThirdPaperTopics(): Promise<Array<ThirdPaperTopic>>;
    getThirdPaperVideos(): Promise<Array<ThirdPaperVideo>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVideoBookmarks(): Promise<Array<DocumentIdentifier>>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    unbookmarkNote(noteId: NoteIdentifier): Promise<void>;
    unbookmarkVideo(documentId: DocumentIdentifier): Promise<void>;
    updateSyllabusEntry(index: bigint, entry: SyllabusEntry): Promise<void>;
}
import type { UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addComment(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async addGKNote(arg0: GKNote): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGKNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGKNote(arg0);
            return result;
        }
    }
    async addGKTopic(arg0: GKTopic): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGKTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGKTopic(arg0);
            return result;
        }
    }
    async addGKVideo(arg0: GKVideo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGKVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGKVideo(arg0);
            return result;
        }
    }
    async addIQCategory(arg0: IQCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addIQCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIQCategory(arg0);
            return result;
        }
    }
    async addIQNote(arg0: IQNote): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addIQNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIQNote(arg0);
            return result;
        }
    }
    async addIQVideo(arg0: IQVideo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addIQVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIQVideo(arg0);
            return result;
        }
    }
    async addMockExam(arg0: MockExam): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMockExam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMockExam(arg0);
            return result;
        }
    }
    async addOldQuestion(arg0: OldQuestion): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOldQuestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOldQuestion(arg0);
            return result;
        }
    }
    async addSecondPaperNote(arg0: SecondPaperNote): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSecondPaperNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSecondPaperNote(arg0);
            return result;
        }
    }
    async addSecondPaperTopic(arg0: SecondPaperTopic): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSecondPaperTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSecondPaperTopic(arg0);
            return result;
        }
    }
    async addSecondPaperVideo(arg0: SecondPaperVideo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSecondPaperVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSecondPaperVideo(arg0);
            return result;
        }
    }
    async addStandaloneNote(arg0: StandaloneNote): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStandaloneNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStandaloneNote(arg0);
            return result;
        }
    }
    async addStandaloneVideo(arg0: StandaloneVideo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStandaloneVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStandaloneVideo(arg0);
            return result;
        }
    }
    async addSyllabusEntry(arg0: SyllabusEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSyllabusEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSyllabusEntry(arg0);
            return result;
        }
    }
    async addThirdPaperNote(arg0: ThirdPaperNote): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addThirdPaperNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addThirdPaperNote(arg0);
            return result;
        }
    }
    async addThirdPaperTopic(arg0: ThirdPaperTopic): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addThirdPaperTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addThirdPaperTopic(arg0);
            return result;
        }
    }
    async addThirdPaperVideo(arg0: ThirdPaperVideo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addThirdPaperVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addThirdPaperVideo(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookmarkNote(arg0: NoteIdentifier): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bookmarkNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookmarkNote(arg0);
            return result;
        }
    }
    async bookmarkVideo(arg0: DocumentIdentifier): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bookmarkVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookmarkVideo(arg0);
            return result;
        }
    }
    async deleteGKTopic(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGKTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGKTopic(arg0);
            return result;
        }
    }
    async deleteGKVideo(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGKVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGKVideo(arg0);
            return result;
        }
    }
    async deleteIQCategory(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIQCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIQCategory(arg0);
            return result;
        }
    }
    async deleteIQVideo(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIQVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIQVideo(arg0);
            return result;
        }
    }
    async deleteMockExam(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMockExam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMockExam(arg0);
            return result;
        }
    }
    async deleteOldQuestion(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOldQuestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOldQuestion(arg0);
            return result;
        }
    }
    async deleteSecondPaperTopic(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSecondPaperTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSecondPaperTopic(arg0);
            return result;
        }
    }
    async deleteSecondPaperVideo(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSecondPaperVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSecondPaperVideo(arg0);
            return result;
        }
    }
    async deleteStandaloneNote(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStandaloneNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStandaloneNote(arg0);
            return result;
        }
    }
    async deleteStandaloneVideo(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStandaloneVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStandaloneVideo(arg0);
            return result;
        }
    }
    async deleteSyllabusEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSyllabusEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSyllabusEntry(arg0);
            return result;
        }
    }
    async deleteThirdPaperTopic(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteThirdPaperTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteThirdPaperTopic(arg0);
            return result;
        }
    }
    async deleteThirdPaperVideo(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteThirdPaperVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteThirdPaperVideo(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComments(): Promise<Array<Array<string>>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments();
            return result;
        }
    }
    async getGKNotes(): Promise<Array<GKNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGKNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGKNotes();
            return result;
        }
    }
    async getGKTopics(): Promise<Array<GKTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGKTopics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGKTopics();
            return result;
        }
    }
    async getGKVideos(): Promise<Array<GKVideo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGKVideos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGKVideos();
            return result;
        }
    }
    async getIQCategories(): Promise<Array<IQCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIQCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIQCategories();
            return result;
        }
    }
    async getIQNotes(): Promise<Array<IQNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIQNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIQNotes();
            return result;
        }
    }
    async getIQVideos(): Promise<Array<IQVideo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIQVideos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIQVideos();
            return result;
        }
    }
    async getMockExams(): Promise<Array<MockExam>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMockExams();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMockExams();
            return result;
        }
    }
    async getNoteBookmarks(): Promise<Array<NoteIdentifier>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNoteBookmarks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNoteBookmarks();
            return result;
        }
    }
    async getOldQuestions(): Promise<Array<OldQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOldQuestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOldQuestions();
            return result;
        }
    }
    async getSecondPaperNotes(): Promise<Array<SecondPaperNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSecondPaperNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSecondPaperNotes();
            return result;
        }
    }
    async getSecondPaperTopics(): Promise<Array<SecondPaperTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSecondPaperTopics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSecondPaperTopics();
            return result;
        }
    }
    async getSecondPaperVideos(): Promise<Array<SecondPaperVideo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSecondPaperVideos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSecondPaperVideos();
            return result;
        }
    }
    async getStandaloneNotes(): Promise<Array<StandaloneNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStandaloneNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStandaloneNotes();
            return result;
        }
    }
    async getStandaloneVideos(): Promise<Array<StandaloneVideo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStandaloneVideos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStandaloneVideos();
            return result;
        }
    }
    async getSyllabusEntries(): Promise<Array<SyllabusEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSyllabusEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSyllabusEntries();
            return result;
        }
    }
    async getThirdPaperNotes(): Promise<Array<ThirdPaperNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getThirdPaperNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThirdPaperNotes();
            return result;
        }
    }
    async getThirdPaperTopics(): Promise<Array<ThirdPaperTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getThirdPaperTopics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThirdPaperTopics();
            return result;
        }
    }
    async getThirdPaperVideos(): Promise<Array<ThirdPaperVideo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getThirdPaperVideos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThirdPaperVideos();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoBookmarks(): Promise<Array<DocumentIdentifier>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoBookmarks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoBookmarks();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async unbookmarkNote(arg0: NoteIdentifier): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unbookmarkNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unbookmarkNote(arg0);
            return result;
        }
    }
    async unbookmarkVideo(arg0: DocumentIdentifier): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unbookmarkVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unbookmarkVideo(arg0);
            return result;
        }
    }
    async updateSyllabusEntry(arg0: bigint, arg1: SyllabusEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSyllabusEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSyllabusEntry(arg0, arg1);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
